### ISSUE TITLE
404 in Firefox addon?

### ISSUE THREAD

**Issue by beep** [MLTSHP/mltshp_plugins#3]
Just tried saving an image, and the extension popped up with a 404 error:

![screen shot 2017-08-03 at 9 48 58 am](https://user-images.githubusercontent.com/124493/28924834-0b20d594-7831-11e7-9fb1-11862dc39305.png)

**Comment by ardgedee** [comment]
@beep Does this problem still occur?

**Comment by beep** [comment]
@ardgedee It does _not_. Thank you!
